sudo: false
language: c
cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev
      - gcc
      - make
      - ruby
      - ruby-dev
      - rpm
      - libclang-3.9-dev
  homebrew:
    packages:
      - libyaml
      - llvm@3.9

matrix:
  fast_finish: true
  include:
  - stage: Test
    name: linux-gcc
    os: linux
    env: KIT_BUILD_TOOLCHAIN=linux-gcc
  - stage: Test
    name: linux-clang
    os: linux
    env: KIT_BUILD_TOOLCHAIN=linux-clang
  - stage: Test
    name: darwin-gcc
    os: osx
    env: KIT_BUILD_TOOLCHAIN=darwin-gcc
  - stage: Test
    name: darwin-clang
    os: osx
    env: KIT_BUILD_TOOLCHAIN=darwin-clang
  - stage: Test
    name: windows-mingw
    os: windows
    env: KIT_BUILD_TOOLCHAIN=windows-mingw


  - stage: Upload
    name: upload Linux packages
    if: env(TRAVIS_PULL_REQUEST) = "false"
    os: linux
    script: 'bash ./.packages/linux.sh'
  - stage: Upload
    name: upload MacOS package
    if: env(TRAVIS_PULL_REQUEST) = "false"
    os: osx
    script: 'bash ./.packages/osx.sh'

  - stage: Test Package Install
    name: "test Linux package install"
    if: branch IN (master, dev) AND env(TRAVIS_PULL_REQUEST) = "false"
    os: linux
    env:
    - KIT_BUILD_TOOLCHAIN: linux-gcc
    before_install: skip
    install: skip
    script: 'bash ./.packages/install_test.sh'

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CLANG_PURE_LLVM_LIB_DIR=/usr/local/opt/llvm@3.9/lib;
      export CLANG_PURE_LLVM_INCLUDE_DIR=/usr/local/opt/llvm@3.9/include;
      travis_retry curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export CLANG_PURE_LLVM_LIB_DIR=/usr/lib/llvm-3.9/lib;
      export CLANG_PURE_LLVM_INCLUDE_DIR=/usr/lib/llvm-3.9/include;
      travis_retry curl -L https://get.haskellstack.org/stable/windows-x86_64.tar.gz | tar xz --strip-components=1 -C ~/.local/bin --wildcards '*/stack.exe';
    fi
  - "gcc --version"
  - "clang --version"

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack build kitlang:kitc
  - stack exec kitc -- -h
  - stack exec kitc -- --env
  - TEST_RUNS=1 stack test --test-arguments '+RTS -N -RTS'
  - stack install

notifications:
  webhooks:
    urls:
    - https://discordapp.com/api/webhooks/531220869075435520/8jqea-tWQhozjCKAWVFnZ7LwWyirOH3tzMKWxnbymIflVUYWrMJ2NhgbUYMUAA2hQcyJ
    - https://webhooks.gitter.im/e/527960c420198d3dc02a
    on_success: change
    on_failure: always
    on_start: never
  email:
    on_success: change
    on_failure: change
